### ISSUE TITLE
pprof/goroutine returns 404

### ISSUE THREAD

**Issue by splucs** [palantir/witchcraft-go-server#110]
pprof includes an endpoint named `goroutine` which returna a stack trace of all current go routines. However, when trying to access this endpoint, the server returns a message `404 page not found`.

**Comment by bmoylan** [comment]
We don't register all routes implemented in net/pprof. The debug routes are documented in the [readme](https://github.com/palantir/witchcraft-go-server#debug-routes) and implemented in [server_routes.go](https://github.com/palantir/witchcraft-go-server/blob/develop/witchcraft/server_routes.go#L123)

I would normally say we could add this route, but I'm a little worried that goroutine dumps include unsafe parameter information. If you can send a `QUIT` signal to the process, it will emit a diagnostic.1 thread dump which is known to be safe for exfiltration ([docs](https://github.com/palantir/witchcraft-go-server#sigquit-handling)). If we had to add this as and endpoint, I'd probably return this JSON object rather than the raw goroutine dump.

**Comment by tabboud** [comment]
Debug diagnostics including goroutine dumps have recently been added https://github.com/palantir/witchcraft-go-server#debug--diagnostic-routes
