### ISSUE TITLE
log canceled request as 499 instead of 500

### ISSUE THREAD

**Issue by bryanhanner** [palantir/witchcraft-go-server#133]
The server currently responds to any request, even if the request is canceled. This makes it possible for the client to receive an error (for example) related to a request they no longer care about. Based on a current need to not send such errors, the needed change seems like a reasonable behavior to extend to the underlying server for the general case. Nick Miyake was very helpful in researching that the implementation would be doable.

I'm specifically proposing adding an opt-in configuration that if enabled would wrap the http.ResponseWriter to not write a response if the request is canceled (which is bidirectionally correlated to the parent context from the request being canceled as per https://golang.org/pkg/net/http/#Request.Context). To help with telemetry, I'm also proposing request logs with a 499 Client Closed Request status code (part of an nginx extension of HTTP status codes) in these cases.

Specifically looking for feedback from @k-simons @bmoylan @jdhenke Thanks!

**Comment by nmiyake** [comment]
As I understand it, the most pertinent/concrete request is to allow the following behavior:

* If the client cancels the request, do not write any response

The secondary/related proposal seems to be:

* In this scenario, log a 499 in the request log as the response code for the request (even though no response was actually sent)
* It would naturally follow that response error metric would also not be incremented (since that only happens on 5xx responses)

From an implementation perspective, all of this should be doable.

For the first bullet, we could make it such that the router always wraps the `http.ResponseWriter` passed to the handler with a handler that writes nothing if the request is cancelled. In this construction, the clients may still invoke write operations, but this wrapper would effectively make those no-ops. Only thing to keep in mind here is that there may be some disconnects with things like logging response writers (these writers store things like the response code and response size as internal state -- these would continue to record what was passed to them, even though the inner wrapped writer will not actually perform the writes)

For the second and third bullet, we can directly modify the middleware that records the metrics such that they check the request status and modify what is recorded if it is cancelled.

One thing we'd want to keep in mind for implementation is possible coordination -- if the request is cancelled after the response write happens but before the metric/request log is written, there could be a mismatch there unless some coordination state is shared.

**Comment by nmiyake** [comment]
The other possible approach would be to just provide a wrapper that implements functionality that actually writes a 499 response (rather than writing no response) if the request is cancelled. We could provide the option to enable/build this into the popular request handlers like `rest.NewJSONHandler` and also provide it as a stand-along handler.

This approach would require no core changes to w-g-s itself (beyond adding the library function), but would require clients that want this behavior to warp their handlers properly to get it.

**Comment by bryanhanner** [comment]
To give my updated two-cents, it seems like this second option to write the 499 is more elegant since there is no need to directly modify the middleware and we avoid the coordination issues. Am I understanding that correctly?

**Comment by jdhenke** [comment]
@bryanhanner can you provide a quick repro of this? How does a client cancel the request then still get a response exactly?

**Comment by bryanhanner** [comment]
@jdhenke as a quick update, I got a chance to try reproing this in a go client, but it seems that I'll need to use a Java client to do the repro as it has to do with some particulars as to how Java futures work. However, there was an investigation that verified this was happening in the following scenario: a java process runs an http request in a thread, and the process then interrupts that thread.

**Comment by bryanhanner** [comment]
@jdhenke there was some miscommunication about what was happening, and it turns out that the client still receiving a response after disconnecting is indeed impossible (which makes sense). This just turns into a logging change to log a 499 on the server side if the context is canceled instead of a 500. @nmiyake would that still be done by writing a 499 response, or is there a simpler way to just change the logging?

**Comment by bryanhanner** [comment]
To play devil's advocate, it's important to note that changing these errors to 499's would obfuscate server errors that occur on canceled request that are unrelated to the request being canceled. I don't have enough perspective to say which would give a more useful signal.

Update: this may not be a complete tradeoff if the 499 would include context of any underlying error.

**Comment by bryanhanner** [comment]
Closing since it is most aligned with Witchcraft's design to leave these sort of decisions up to each handler as to what status code is returned (and what is, in turn, logged)
